name: AFK
version: "${pom.version}"
api: ["1.0.0"]
author: PetteriM1
main: idk.plugin.afk.Main

commands:
  afk:
    description: Mark you as AFK
    usage: "/afk"
    permission: afk
permissions:
  afk:
    description: "Allows player to use /afk"
    default: true
